### ISSUE TITLE
Using real IP instead of server's

### ISSUE THREAD

**Issue by Ezerbeth** [prawnsalad/KiwiIRC#888]
Hello,

There desperately needs to be an option to display the real client IP, not the server. Can't find anything in documentation and if I have 5 clients connecting, they all appear online with server.domain.com instead of their real IP. So if I try to ban one, I ban all of them. Kinda makes this client completely useless...

**Comment by CoryChaplin** [comment]
Hi,

There is such an option, just register your network and configure a web irc
block.
That works just fine on hundreds of networks.

-- 
Elephantman

De :  Ezerbeth <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5ac053b865b374a3d17ff4672aeeebceb1607ff4092cf0000000113a0b63e9
2a169ce09e1ea5f@reply.github.com>
Date :  vendredi 15 juillet 2016 16:33
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [prawnsalad/KiwiIRC] Using real IP instead of server's (#888)

**Comment by Ezerbeth** [comment]
So thanks for confirming there is no option. IRC block is configured and it still appears as server.domain.com. There's no register option anywhere to "register my network".

**Comment by prawnsalad** [comment]
@Ezerbeth He said the very opposite, there *is* the option to pass the user IPs to the networks, as proven by thousands of other networks.

Are you using your own kiwiirc server? Take a look here: https://kiwiirc.com/docs/installing/webirc

Are you using kiwiirc.com? Take a look here: https://kiwiirc.com/enablekiwi to register your network, then enter the webirc/cgiirc config block it gives you into your IRCd correctly and rehash your IRCd.
